name: flura_capsa
description: Integration package between Flura Core and Capsa. Manages Capsa lifecycle, ScreenModel registration, and reactive engine integration.
version: 0.1.0
publish_to: none
repository: https://github.com/pishguy/flura

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flura_core:
    path: ../flura_core
  capsa:
    path: /Users/mahdipishguy/Desktop/projects/flutter/capsa

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
