name: flura_testing
description: Testing utilities for the Flura framework. Provides FakeApplication, temp database helpers, container overrides, and reactive test helpers.
version: 0.1.0
publish_to: none
repository: https://github.com/pishguy/flura

environment:
  sdk: ^3.10.0

dependencies:
  flura_core:
    path: ../flura_core
  flutter_facades:
    path: /Users/mahdipishguy/Desktop/projects/flutter/flutter_facades

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
